sudo: false
language: ruby
rvm:
  - 2.5
env:
  global:
    - PGPORT: "5433"
  jobs:
    - PGVERSION: "9.6"
    - PGVERSION: "10"
    - PGVERSION: "11"
    - PGVERSION: "12"
services:
  - postgresql
before_install:
  - "for CLUSTER_VERSION in $(pg_lsclusters -h | cut -d' ' -f1); do sudo pg_dropcluster $CLUSTER_VERSION main --stop || true; sudo apt-get remove postgresql-client-$CLUSTER_VERSION postgresql-client-common || true; done"
  - sudo apt-get update
  - sudo apt-get -y install postgresql-$PGVERSION postgresql-server-dev-$PGVERSION postgresql-contrib-$PGVERSION postgresql-client-$PGVERSION postgresql-client-common
  - sudo pg_dropcluster $PGVERSION main --stop || true
  - sudo pg_createcluster $PGVERSION main -D /var/ramfs/postgresql/11/main -- --auth=trust
  - sudo pg_ctlcluster start $PGVERSION main
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v 1.15.4
gemfile:
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
script: "bundle exec rake spec"
